spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        format_sql= true:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


  mongodb:
    host: localhost
    port: 27017
    database: your_database_name
    username: your_username
    password: your_password
    uri: mongodb://[username:password@]host:port/database # Alternative to host/port/database


  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK